/*
 * THIS FILE IS AUTOMATICALLY GENERATED
 *
 * Generator:     sensirion-driver-generator 0.40.1
 * Product:       sfx6xxx
 * Model-Version: 2.3.1
 */
/*
 * Copyright (c) 2024, Sensirion AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of Sensirion AG nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
#include "sensirion_common.h"
#include "sensirion_i2c_hal.h"
#include "sfx6xxx_i2c.h"
#include <inttypes.h>  // PRIx64
#include <stdio.h>     // printf

#define sensirion_hal_sleep_us sensirion_i2c_hal_sleep_usec

int main(void) {
    int16_t error = NO_ERROR;
    sensirion_i2c_hal_init();
    sfx6xxx_init(SFC6000_I2C_ADDR_24);

    uint32_t product_identifier = 0;
    uint64_t serial_number = 0;
    error =
        sfx6xxx_read_product_identifier(&product_identifier, &serial_number);
    if (error != NO_ERROR) {
        printf("error executing read_product_identifier(): %i\n", error);
        return error;
    }
    printf("product_identifier: %u ", product_identifier);
    printf("serial_number: %" PRIx64 "\n", serial_number);
    error = sfx6xxx_start_o2_continuous_measurement();
    if (error != NO_ERROR) {
        printf("error executing start_o2_continuous_measurement(): %i\n",
               error);
        return error;
    }
    float a_flow = 0.0;
    uint16_t repetition = 0;
    for (repetition = 0; repetition < 100; repetition++) {
        sensirion_hal_sleep_us(500000);
        error = sfx6xxx_read_flow(&a_flow);
        if (error != NO_ERROR) {
            printf("error executing read_flow(): %i\n", error);
            continue;
        }
        printf("a_flow: %.2f\n", a_flow);
    }

    error = sfx6xxx_stop_continuous_measurement();
    if (error != NO_ERROR) {
        return error;
    }
    return NO_ERROR;
}
